theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "version-control", # Added
  "read-only-indicator",
  "file-modification-indicator"
]
right = [
  "diagnostics",
  "file-indent-style", # Added
  "file-type", # Added
  "selections",
  "register",
  "position",
  "total-line-numbers", # Added
  "file-encoding"
]

[keys.normal.space]
x = ":bc"
